# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QGroupBox,
    QLabel, QLineEdit, QMenu, QPushButton,
    QSizePolicy, QToolButton, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1025, 431)
        self.ManageCustomTransducersAction = QAction(Dialog)
        self.ManageCustomTransducersAction.setObjectName(u"ManageCustomTransducersAction")
        self.SettingsToolButton = QToolButton(Dialog)
        self.SettingsToolButton.setObjectName(u"SettingsToolButton")
        self.SettingsToolButton.setGeometry(QRect(985, 2, 30, 24))
        self.SettingsToolButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.SettingsToolButton.setStyleSheet(u"QToolButton { border: none; font-size: 18px; }\n"
"QToolButton:hover { background-color: rgba(128, 128, 128, 40); border-radius: 4px; }\n"
"QToolButton::menu-indicator { image: none; }")
        self.SettingsToolButton.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)
        self.SettingsToolButton.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.SettingsToolButton.setAutoRaise(True)
        self.SettingsMenu = QMenu(self.SettingsToolButton)
        self.SettingsMenu.setObjectName(u"SettingsMenu")
        self.ContinuepushButton = QPushButton(Dialog)
        self.ContinuepushButton.setObjectName(u"ContinuepushButton")
        self.ContinuepushButton.setGeometry(QRect(378, 391, 239, 32))
        self.groupBox = QGroupBox(SelFilesDialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(6, 3, 1014, 262))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"")
        self.CoregCTlabel = QLabel(self.groupBox)
        self.CoregCTlabel.setObjectName(u"CoregCTlabel")
        self.CoregCTlabel.setEnabled(False)
        self.CoregCTlabel.setGeometry(QRect(41, 165, 58, 16))
        self.SelT1WpushButton = QPushButton(self.groupBox)
        self.SelT1WpushButton.setObjectName(u"SelT1WpushButton")
        self.SelT1WpushButton.setGeometry(QRect(238, 91, 153, 32))
        self.SelT1WpushButton.setStyleSheet(u"")
        self.SelT1WpushButton.setAutoDefault(False)
        self.SelT1WpushButton.setFlat(False)
        self.SelCTpushButton = QPushButton(self.groupBox)
        self.SelCTpushButton.setObjectName(u"SelCTpushButton")
        self.SelCTpushButton.setEnabled(False)
        self.SelCTpushButton.setGeometry(QRect(238, 129, 153, 30))
        self.SelCTpushButton.setStyleSheet(u"")
        self.SelCTpushButton.setAutoDefault(False)
        self.SelCTpushButton.setFlat(False)
        self.SimbNIBSlineEdit = QLineEdit(self.groupBox)
        self.SimbNIBSlineEdit.setObjectName(u"SimbNIBSlineEdit")
        self.SimbNIBSlineEdit.setGeometry(QRect(400, 63, 607, 21))
        self.SimbNIBSlineEdit.setStyleSheet(u"")
        self.SelTProfilepushButton = QPushButton(self.groupBox)
        self.SelTProfilepushButton.setObjectName(u"SelTProfilepushButton")
        self.SelTProfilepushButton.setGeometry(QRect(204, 219, 187, 42))
        self.SelTProfilepushButton.setStyleSheet(u"")
        self.SelTProfilepushButton.setAutoDefault(False)
        self.SelTProfilepushButton.setFlat(False)
        self.ThermalProfilelineEdit = QLineEdit(self.groupBox)
        self.ThermalProfilelineEdit.setObjectName(u"ThermalProfilelineEdit")
        self.ThermalProfilelineEdit.setGeometry(QRect(400, 230, 607, 21))
        self.ThermalProfilelineEdit.setStyleSheet(u"")
        self.CTlineEdit = QLineEdit(self.groupBox)
        self.CTlineEdit.setObjectName(u"CTlineEdit")
        self.CTlineEdit.setEnabled(False)
        self.CTlineEdit.setGeometry(QRect(400, 134, 604, 21))
        self.CTlineEdit.setStyleSheet(u"")
        self.CTlineEdit.setCursorPosition(3)
        self.T1WlineEdit = QLineEdit(self.groupBox)
        self.T1WlineEdit.setObjectName(u"T1WlineEdit")
        self.T1WlineEdit.setGeometry(QRect(400, 96, 607, 21))
        self.T1WlineEdit.setStyleSheet(u"")
        self.CTTypecomboBox = QComboBox(self.groupBox)
        self.CTTypecomboBox.addItem(u"NO")
        self.CTTypecomboBox.addItem(u"real CT")
        self.CTTypecomboBox.addItem(u"ZTE")
        self.CTTypecomboBox.addItem(u"PETRA")
        self.CTTypecomboBox.addItem(u"Density")
        self.CTTypecomboBox.setObjectName(u"CTTypecomboBox")
        self.CTTypecomboBox.setGeometry(QRect(110, 125, 110, 30))
        self.CTTypecomboBox.setStyleSheet(u"")
        self.SelSimbNIBSpushButton = QPushButton(self.groupBox)
        self.SelSimbNIBSpushButton.setObjectName(u"SelSimbNIBSpushButton")
        self.SelSimbNIBSpushButton.setGeometry(QRect(238, 58, 152, 32))
        self.SelSimbNIBSpushButton.setStyleSheet(u"")
        self.SelSimbNIBSpushButton.setAutoDefault(False)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-8, 114, 108, 48))
        self.label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.SelTrajectorypushButton = QPushButton(self.groupBox)
        self.SelTrajectorypushButton.setObjectName(u"SelTrajectorypushButton")
        self.SelTrajectorypushButton.setGeometry(QRect(238, 23, 152, 32))
        self.SelTrajectorypushButton.setStyleSheet(u"")
        self.SelTrajectorypushButton.setAutoDefault(False)
        self.TrajectorylineEdit = QLineEdit(self.groupBox)
        self.TrajectorylineEdit.setObjectName(u"TrajectorylineEdit")
        self.TrajectorylineEdit.setGeometry(QRect(400, 28, 607, 21))
        self.TrajectorylineEdit.setStyleSheet(u"")
        self.TrajectoryTypecomboBox = QComboBox(self.groupBox)
        self.TrajectoryTypecomboBox.addItem(u"Brainsight")
        self.TrajectoryTypecomboBox.addItem(u"Slicer")
        self.TrajectoryTypecomboBox.addItem(u"Localite")
        self.TrajectoryTypecomboBox.setObjectName(u"TrajectoryTypecomboBox")
        self.TrajectoryTypecomboBox.setGeometry(QRect(110, 25, 110, 30))
        self.TrajectoryTypecomboBox.setStyleSheet(u"")
        self.CoregCTcomboBox = QComboBox(self.groupBox)
        self.CoregCTcomboBox.addItem(u"NO")
        self.CoregCTcomboBox.addItem(u"CT to MRI")
        self.CoregCTcomboBox.setObjectName(u"CoregCTcomboBox")
        self.CoregCTcomboBox.setEnabled(False)
        self.CoregCTcomboBox.setGeometry(QRect(110, 160, 110, 30))
        self.CoregCTcomboBox.setStyleSheet(u"")
        self.SimbNIBSTypecomboBox = QComboBox(self.groupBox)
        self.SimbNIBSTypecomboBox.addItem(u"charm")
        self.SimbNIBSTypecomboBox.addItem(u"headreco")
        self.SimbNIBSTypecomboBox.setObjectName(u"SimbNIBSTypecomboBox")
        self.SimbNIBSTypecomboBox.setGeometry(QRect(110, 72, 110, 25))
        self.SimbNIBSTypecomboBox.setStyleSheet(u"")
        self.CoregCTlabel_2 = QLabel(self.groupBox)
        self.CoregCTlabel_2.setObjectName(u"CoregCTlabel_2")
        self.CoregCTlabel_2.setEnabled(False)
        self.CoregCTlabel_2.setGeometry(QRect(310, 193, 81, 20))
        self.CTMappingcomboBox = QComboBox(self.groupBox)
        self.CTMappingcomboBox.setObjectName(u"CTMappingcomboBox")
        self.CTMappingcomboBox.setEnabled(False)
        self.CTMappingcomboBox.setGeometry(QRect(400, 188, 377, 32))
        self.CoregCTlabel_3 = QLabel(self.groupBox)
        self.CoregCTlabel_3.setObjectName(u"CoregCTlabel_3")
        self.CoregCTlabel_3.setEnabled(False)
        self.CoregCTlabel_3.setGeometry(QRect(450, 166, 281, 20))
        self.ResetCTMapOriginalpushButton = QPushButton(self.groupBox)
        self.ResetCTMapOriginalpushButton.setObjectName(u"ResetCTMapOriginalpushButton")
        self.ResetCTMapOriginalpushButton.setEnabled(False)
        self.ResetCTMapOriginalpushButton.setGeometry(QRect(780, 188, 136, 32))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(-6, 23, 92, 25))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(-2, 73, 92, 20))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.groupBox_2 = QGroupBox(SelFilesDialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(8, 266, 1010, 117))
        self.groupBox_2.setStyleSheet(u"")
        self.TransducerTypecomboBox = QComboBox(self.groupBox_2)
        self.TransducerTypecomboBox.setObjectName(u"TransducerTypecomboBox")
        self.TransducerTypecomboBox.setGeometry(QRect(90, 30, 116, 30))
        self.TransducerTypecomboBox.setStyleSheet(u"")
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(15, 36, 71, 16))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 32, 121, 20))
        self.ComputingEnginecomboBox = QComboBox(self.groupBox_2)
        self.ComputingEnginecomboBox.setObjectName(u"ComputingEnginecomboBox")
        self.ComputingEnginecomboBox.setGeometry(QRect(398, 28, 275, 30))
        self.ComputingEnginecomboBox.setStyleSheet(u"")
        self.MultiPointTypecomboBox = QComboBox(self.groupBox_2)
        self.MultiPointTypecomboBox.addItem(u"NO")
        self.MultiPointTypecomboBox.addItem(u"YES")
        self.MultiPointTypecomboBox.setObjectName(u"MultiPointTypecomboBox")
        self.MultiPointTypecomboBox.setEnabled(False)
        self.MultiPointTypecomboBox.setGeometry(QRect(110, 73, 82, 30))
        self.MultiPointTypecomboBox.setStyleSheet(u"")
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(8, 78, 102, 16))
        self.MultiPointlineEdit = QLineEdit(self.groupBox_2)
        self.MultiPointlineEdit.setObjectName(u"MultiPointlineEdit")
        self.MultiPointlineEdit.setEnabled(False)
        self.MultiPointlineEdit.setGeometry(QRect(400, 77, 607, 21))
        self.MultiPointlineEdit.setStyleSheet(u"")
        self.MultiPointlineEdit.setCursorPosition(3)
        self.SelMultiPointProfilepushButton = QPushButton(self.groupBox_2)
        self.SelMultiPointProfilepushButton.setObjectName(u"SelMultiPointProfilepushButton")
        self.SelMultiPointProfilepushButton.setEnabled(False)
        self.SelMultiPointProfilepushButton.setGeometry(QRect(198, 67, 192, 42))
        self.SelMultiPointProfilepushButton.setStyleSheet(u"")
        self.SelMultiPointProfilepushButton.setAutoDefault(False)
        self.SelMultiPointProfilepushButton.setFlat(False)
        self.CancelpushButton = QPushButton(SelFilesDialog)
        self.CancelpushButton.setObjectName(u"CancelpushButton")
        self.CancelpushButton.setGeometry(QRect(945, 392, 74, 32))

        self.SettingsToolButton.addAction(self.SettingsMenu.menuAction())
        self.SettingsMenu.addAction(self.ManageCustomTransducersAction)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(SelFilesDialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.ManageCustomTransducersAction.setText(QCoreApplication.translate("Dialog", u"Manage Custom Transducers", None))
#if QT_CONFIG(tooltip)
        self.SettingsToolButton.setToolTip(QCoreApplication.translate("Dialog", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.SettingsToolButton.setText(QCoreApplication.translate("Dialog", u"\u2699", None))
        self.SettingsMenu.setTitle("")
        self.ContinuepushButton.setText(QCoreApplication.translate("Dialog", u"CONTINUE", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Imaging input", None))
        self.CoregCTlabel.setText(QCoreApplication.translate("Dialog", u"Correg.?", None))
        self.SelT1WpushButton.setText(QCoreApplication.translate("Dialog", u"Select T1W ...", None))
        self.SelCTpushButton.setText(QCoreApplication.translate("Dialog", u"Select", None))
        self.SimbNIBSlineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.SelTProfilepushButton.setText(QCoreApplication.translate("Dialog", u"Select Thermal Profile ...", None))
        self.ThermalProfilelineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.CTlineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.T1WlineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.CTTypecomboBox.setItemText(0, QCoreApplication.translate("Dialog", u"NO", None))
        self.CTTypecomboBox.setItemText(1, QCoreApplication.translate("Dialog", u"real CT", None))
        self.CTTypecomboBox.setItemText(2, QCoreApplication.translate("Dialog", u"ZTE", None))
        self.CTTypecomboBox.setItemText(3, QCoreApplication.translate("Dialog", u"PETRA", None))
        self.CTTypecomboBox.setItemText(4, QCoreApplication.translate("Dialog", u"Density", None))

        self.SelSimbNIBSpushButton.setText(QCoreApplication.translate("SelFilesDialog", u"Select SimbNIBS ...", None))
        self.label.setText(QCoreApplication.translate("SelFilesDialog", u"Use CT, ZTE,\n"
"PETRA, Density?", None))
        self.SelTrajectorypushButton.setText(QCoreApplication.translate("SelFilesDialog", u"Select Trajectory ...", None))
        self.TrajectorylineEdit.setText(QCoreApplication.translate("SelFilesDialog", u"...", None))



        self.CoregCTlabel_2.setText(QCoreApplication.translate("Dialog", u"CT Mapping", None))
        self.CoregCTlabel_3.setText(QCoreApplication.translate("Dialog", u"Scanner ,Energy, Kernel, Other, Resolution", None))
        self.ResetCTMapOriginalpushButton.setText(QCoreApplication.translate("Dialog", u"Reset to original", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Trajectory type", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"SimNIBS type", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Transducer and Computing engine", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Transducer", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Computing backend", None))
        self.MultiPointTypecomboBox.setItemText(0, QCoreApplication.translate("Dialog", u"NO", None))
        self.MultiPointTypecomboBox.setItemText(1, QCoreApplication.translate("Dialog", u"YES", None))

        self.label_4.setText(QCoreApplication.translate("SelFilesDialog", u"Use Mulltipoint?", None))
        self.MultiPointlineEdit.setText(QCoreApplication.translate("SelFilesDialog", u"...", None))
        self.SelMultiPointProfilepushButton.setText(QCoreApplication.translate("SelFilesDialog", u"Select Multi-Point Profile ...", None))
        self.CancelpushButton.setText(QCoreApplication.translate("SelFilesDialog", u"Cancel", None))
    # retranslateUi

