TxDiam:                   64.0e-3    #in m
FocalLength:              62.94e-3  #in m
NaturalOutPlaneDistance:  52.38e-3  # in m
MinimalTPODistance:       25.0e-3  # in m
MaximalTPODistance:       60.0e-3  # in m
USFrequencies:
    - 250000.0
MaxNegativeDistance:          10.0 #mm
MaxDistanceToSkin:            50.00 #mm
InDiameters: #inner diameter of rings
    - 0.0
    - 30.1788e-3
    - 42.1388e-3
    - 51.1088e-3
OutDiameters:  #outer diameter of rings
    - 29.62e-3
    - 41.58e-3
    - 50.55e-3
    - 57.94e-3
Corrections:
    Original:
        - 0.0
        - 0.0
        - 0.0