TxDiam:                58.0e-3 # Tx aperture diameter
MinimalXSteering:      -35.0e-3  # in m
MaximalXSteering:      35.0e-3  # in m
MinimalYSteering:      -35.0e-3  # in m
MaximalYSteering:      35.0e-3  # in m
MinimalZSteering:      20.0e-3  # in m
MaximalZSteering:      100.0e-3  # in m
DefaultZSteering:      30.0e-3  # in m
USFrequencies:
    - 300000.0
    - 480000.0 
    - 490000.0 
MaxNegativeDistance:          10.0 #mm
MaxDistanceToSkin:            50.00 #mm


PlanTUS: #This information is to interface with the PlanTUS tool - Synthectic
    300000.0:
        FocalDistanceList:
            - 10.0
            - 20.0
            - 30.0
            - 40.0
            - 50.0
            - 60.0
            - 70.0
            - 80.0
            - 90.0
            - 100.0
            - 110.0
            - 120.0
            - 130.0
            - 140.0
            - 150.0
        FHMLList:
            - 7.5
            - 11.5
            - 17.0
            - 23.0
            - 30.0
            - 37.5
            - 45.5
            - 52.5
            - 60.0
            - 66.5
            - 73.0
            - 79.0
            - 84.5
            - 89.5
            - 95.0
    480000.0:
        FocalDistanceList:
            - 6.3
            - 12.5
            - 18.8
            - 25.0
            - 31.2
            - 37.5
            - 43.7
            - 50.0
            - 56.2
            - 62.5
            - 68.8
            - 75.0
            - 81.2
            - 87.5
            - 93.8
            - 100.0
            - 106.3
            - 112.5
            - 118.7
            - 125.0
            - 131.2
            - 137.5
            - 143.7
            - 150.0
            - 156.2
        FHMLList:
            - 4.1
            - 5.3
            - 6.9
            - 9.1
            - 11.6
            - 14.4
            - 17.8
            - 21.6
            - 25.6
            - 30.0
            - 34.4
            - 38.8
            - 43.8
            - 48.4
            - 53.4
            - 58.4
            - 63.1
            - 68.1
            - 73.1
            - 77.8
            - 82.5
            - 86.9
            - 91.6
            - 95.9
            - 100.3
    490000.0:
        FocalDistanceList:
            - 6.1
            - 12.2
            - 18.4
            - 24.5
            - 30.6
            - 36.7
            - 42.9
            - 49.0
            - 55.1
            - 61.2
            - 67.3
            - 73.5
            - 79.6
            - 85.7
            - 91.8
            - 98.0
            - 104.1
            - 110.2
            - 116.3
            - 122.4
            - 128.6
            - 134.7
            - 140.8
            - 146.9
            - 153.1
            - 159.2
        FHMLList:
            - 4.0
            - 5.2
            - 6.4
            - 8.6
            - 11.0
            - 13.8
            - 17.1
            - 20.5
            - 24.2
            - 28.5
            - 32.8
            - 37.3
            - 41.9
            - 46.8
            - 51.4
            - 56.0
            - 61.2
            - 65.8
            - 70.7
            - 75.3
            - 79.9
            - 84.5
            - 89.1
            - 93.7
            - 98.0
            - 102.2
