# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QDoubleSpinBox, QGroupBox, QLabel, QPushButton,
    QSizePolicy, QSpinBox, QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(664, 455)
        self.CancelpushButton = QPushButton(Dialog)
        self.CancelpushButton.setObjectName(u"CancelpushButton")
        self.CancelpushButton.setGeometry(QRect(579, 420, 74, 32))
        self.ContinuepushButton = QPushButton(Dialog)
        self.ContinuepushButton.setObjectName(u"ContinuepushButton")
        self.ContinuepushButton.setGeometry(QRect(275, 422, 136, 32))
        self.ResetpushButton = QPushButton(Dialog)
        self.ResetpushButton.setObjectName(u"ResetpushButton")
        self.ResetpushButton.setGeometry(QRect(5, 420, 136, 32))
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(5, 4, 644, 407))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(136, 11, 201, 16))
        self.ElastixOptimizercomboBox = QComboBox(self.tab)
        self.ElastixOptimizercomboBox.addItem("")
        self.ElastixOptimizercomboBox.addItem("")
        self.ElastixOptimizercomboBox.addItem("")
        self.ElastixOptimizercomboBox.setObjectName(u"ElastixOptimizercomboBox")
        self.ElastixOptimizercomboBox.setGeometry(QRect(328, 5, 281, 30))
        self.ElastixOptimizercomboBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ElastixOptimizercomboBox.setStyleSheet(u"")
        self.ForceBlendercheckBox = QCheckBox(self.tab)
        self.ForceBlendercheckBox.setObjectName(u"ForceBlendercheckBox")
        self.ForceBlendercheckBox.setGeometry(QRect(3, 65, 349, 20))
        self.ForceBlendercheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.TrabecularProportionSpinBox = QDoubleSpinBox(self.tab)
        self.TrabecularProportionSpinBox.setObjectName(u"TrabecularProportionSpinBox")
        self.TrabecularProportionSpinBox.setGeometry(QRect(334, 37, 61, 22))
        self.TrabecularProportionSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.TrabecularProportionSpinBox.setDecimals(1)
        self.TrabecularProportionSpinBox.setMinimum(0.000000000000000)
        self.TrabecularProportionSpinBox.setMaximum(1.000000000000000)
        self.TrabecularProportionSpinBox.setSingleStep(0.100000000000000)
        self.TrabecularProportionSpinBox.setValue(1.000000000000000)
        self.FocalLengthLabel_3 = QLabel(self.tab)
        self.FocalLengthLabel_3.setObjectName(u"FocalLengthLabel_3")
        self.FocalLengthLabel_3.setGeometry(QRect(401, 38, 251, 20))
        self.grpManualFOV = QGroupBox(self.tab)
        self.grpManualFOV.setObjectName(u"grpManualFOV")
        self.grpManualFOV.setEnabled(False)
        self.grpManualFOV.setGeometry(QRect(233, 117, 206, 72))
        self.FOVDiameterSpinBox = QDoubleSpinBox(self.grpManualFOV)
        self.FOVDiameterSpinBox.setObjectName(u"FOVDiameterSpinBox")
        self.FOVDiameterSpinBox.setGeometry(QRect(105, 7, 90, 22))
        self.FOVDiameterSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.FOVDiameterSpinBox.setDecimals(1)
        self.FOVDiameterSpinBox.setMinimum(10.000000000000000)
        self.FOVDiameterSpinBox.setMaximum(400.000000000000000)
        self.FOVDiameterSpinBox.setSingleStep(0.100000000000000)
        self.FOVDiameterSpinBox.setValue(200.000000000000000)
        self.DiameterLabel = QLabel(self.grpManualFOV)
        self.DiameterLabel.setObjectName(u"DiameterLabel")
        self.DiameterLabel.setGeometry(QRect(9, 40, 82, 20))
        self.FOVLengthSpinBox = QDoubleSpinBox(self.grpManualFOV)
        self.FOVLengthSpinBox.setObjectName(u"FOVLengthSpinBox")
        self.FOVLengthSpinBox.setGeometry(QRect(105, 40, 90, 22))
        self.FOVLengthSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.FOVLengthSpinBox.setDecimals(1)
        self.FOVLengthSpinBox.setMinimum(200.000000000000000)
        self.FOVLengthSpinBox.setMaximum(600.000000000000000)
        self.FOVLengthSpinBox.setSingleStep(0.100000000000000)
        self.FOVLengthSpinBox.setValue(400.000000000000000)
        self.FocalLengthLabel = QLabel(self.grpManualFOV)
        self.FocalLengthLabel.setObjectName(u"FocalLengthLabel")
        self.FocalLengthLabel.setGeometry(QRect(9, 7, 94, 20))
        self.ManualFOVcheckBox = QCheckBox(self.tab)
        self.ManualFOVcheckBox.setObjectName(u"ManualFOVcheckBox")
        self.ManualFOVcheckBox.setGeometry(QRect(203, 93, 150, 20))
        self.ManualFOVcheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.FocalLengthLabel_2 = QLabel(self.tab)
        self.FocalLengthLabel_2.setObjectName(u"FocalLengthLabel_2")
        self.FocalLengthLabel_2.setGeometry(QRect(151, 37, 181, 20))
        self.InvertZTEcheckBox = QCheckBox(self.tab)
        self.InvertZTEcheckBox.setObjectName(u"InvertZTEcheckBox")
        self.InvertZTEcheckBox.setGeometry(QRect(202, 194, 150, 20))
        self.InvertZTEcheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.DisableCTMedianFiltercheckBox = QCheckBox(self.tab)
        self.DisableCTMedianFiltercheckBox.setObjectName(u"DisableCTMedianFiltercheckBox")
        self.DisableCTMedianFiltercheckBox.setGeometry(QRect(102, 217, 251, 20))
        self.DisableCTMedianFiltercheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.FocalLengthLabel_4 = QLabel(self.tab)
        self.FocalLengthLabel_4.setObjectName(u"FocalLengthLabel_4")
        self.FocalLengthLabel_4.setGeometry(QRect(177, 242, 156, 20))
        self.FocalLengthLabel_5 = QLabel(self.tab)
        self.FocalLengthLabel_5.setObjectName(u"FocalLengthLabel_5")
        self.FocalLengthLabel_5.setGeometry(QRect(90, 270, 241, 20))
        self.GeneratePETRAHistogramcheckBox = QCheckBox(self.tab)
        self.GeneratePETRAHistogramcheckBox.setObjectName(u"GeneratePETRAHistogramcheckBox")
        self.GeneratePETRAHistogramcheckBox.setGeometry(QRect(100, 293, 251, 20))
        self.GeneratePETRAHistogramcheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.FocalLengthLabel_6 = QLabel(self.tab)
        self.FocalLengthLabel_6.setObjectName(u"FocalLengthLabel_6")
        self.FocalLengthLabel_6.setGeometry(QRect(355, 293, 276, 20))
        self.PetraNPeaksSpinBox = QSpinBox(self.tab)
        self.PetraNPeaksSpinBox.setObjectName(u"PetraNPeaksSpinBox")
        self.PetraNPeaksSpinBox.setGeometry(QRect(334, 242, 42, 21))
        self.PetraNPeaksSpinBox.setMinimum(2)
        self.PetraNPeaksSpinBox.setMaximum(50)
        self.PetraMRIPeakDistancespinBox = QSpinBox(self.tab)
        self.PetraMRIPeakDistancespinBox.setObjectName(u"PetraMRIPeakDistancespinBox")
        self.PetraMRIPeakDistancespinBox.setGeometry(QRect(334, 270, 42, 22))
        self.PetraMRIPeakDistancespinBox.setMinimum(10)
        self.PetraMRIPeakDistancespinBox.setMaximum(5000)
        self.PetraMRIPeakDistancespinBox.setValue(50)
        self.ZTESlopeSpinBox = QDoubleSpinBox(self.tab)
        self.ZTESlopeSpinBox.setObjectName(u"ZTESlopeSpinBox")
        self.ZTESlopeSpinBox.setGeometry(QRect(309, 318, 86, 22))
        self.ZTESlopeSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ZTESlopeSpinBox.setDecimals(1)
        self.ZTESlopeSpinBox.setMinimum(-5000.000000000000000)
        self.ZTESlopeSpinBox.setMaximum(5000.000000000000000)
        self.ZTESlopeSpinBox.setSingleStep(10.000000000000000)
        self.ZTESlopeSpinBox.setValue(-2000.000000000000000)
        self.FocalLengthLabel_8 = QLabel(self.tab)
        self.FocalLengthLabel_8.setObjectName(u"FocalLengthLabel_8")
        self.FocalLengthLabel_8.setGeometry(QRect(53, 318, 255, 20))
        self.ZTEOffsetSpinBox = QDoubleSpinBox(self.tab)
        self.ZTEOffsetSpinBox.setObjectName(u"ZTEOffsetSpinBox")
        self.ZTEOffsetSpinBox.setGeometry(QRect(479, 318, 86, 22))
        self.ZTEOffsetSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ZTEOffsetSpinBox.setDecimals(1)
        self.ZTEOffsetSpinBox.setMinimum(-5000.000000000000000)
        self.ZTEOffsetSpinBox.setMaximum(5000.000000000000000)
        self.ZTEOffsetSpinBox.setSingleStep(10.000000000000000)
        self.ZTEOffsetSpinBox.setValue(-2000.000000000000000)
        self.FocalLengthLabel_9 = QLabel(self.tab)
        self.FocalLengthLabel_9.setObjectName(u"FocalLengthLabel_9")
        self.FocalLengthLabel_9.setGeometry(QRect(419, 318, 70, 20))
        self.PETRASlopeSpinBox = QDoubleSpinBox(self.tab)
        self.PETRASlopeSpinBox.setObjectName(u"PETRASlopeSpinBox")
        self.PETRASlopeSpinBox.setGeometry(QRect(309, 342, 86, 22))
        self.PETRASlopeSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.PETRASlopeSpinBox.setDecimals(1)
        self.PETRASlopeSpinBox.setMinimum(-5000.000000000000000)
        self.PETRASlopeSpinBox.setMaximum(5000.000000000000000)
        self.PETRASlopeSpinBox.setSingleStep(10.000000000000000)
        self.PETRASlopeSpinBox.setValue(-2000.000000000000000)
        self.PETRAOffsetSpinBox = QDoubleSpinBox(self.tab)
        self.PETRAOffsetSpinBox.setObjectName(u"PETRAOffsetSpinBox")
        self.PETRAOffsetSpinBox.setGeometry(QRect(479, 342, 86, 22))
        self.PETRAOffsetSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.PETRAOffsetSpinBox.setDecimals(1)
        self.PETRAOffsetSpinBox.setMinimum(-5000.000000000000000)
        self.PETRAOffsetSpinBox.setMaximum(5000.000000000000000)
        self.PETRAOffsetSpinBox.setSingleStep(10.000000000000000)
        self.PETRAOffsetSpinBox.setValue(-2000.000000000000000)
        self.FocalLengthLabel_10 = QLabel(self.tab)
        self.FocalLengthLabel_10.setObjectName(u"FocalLengthLabel_10")
        self.FocalLengthLabel_10.setGeometry(QRect(20, 342, 288, 20))
        self.FocalLengthLabel_11 = QLabel(self.tab)
        self.FocalLengthLabel_11.setObjectName(u"FocalLengthLabel_11")
        self.FocalLengthLabel_11.setGeometry(QRect(419, 342, 70, 20))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(179, 16, 137, 16))
        self.CTX500CorrectioncomboBox = QComboBox(self.tab_2)
        self.CTX500CorrectioncomboBox.addItem("")
        self.CTX500CorrectioncomboBox.addItem("")
        self.CTX500CorrectioncomboBox.setObjectName(u"CTX500CorrectioncomboBox")
        self.CTX500CorrectioncomboBox.setGeometry(QRect(316, 11, 99, 30))
        self.CTX500CorrectioncomboBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.CTX500CorrectioncomboBox.setStyleSheet(u"")
        self.SaveStresscheckBox = QCheckBox(self.tab_2)
        self.SaveStresscheckBox.setObjectName(u"SaveStresscheckBox")
        self.SaveStresscheckBox.setGeometry(QRect(192, 40, 149, 20))
        self.SaveStresscheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.SaveDisplacementcheckBox = QCheckBox(self.tab_2)
        self.SaveDisplacementcheckBox.setObjectName(u"SaveDisplacementcheckBox")
        self.SaveDisplacementcheckBox.setGeometry(QRect(113, 64, 228, 20))
        self.SaveDisplacementcheckBox.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.BaselineTemperatureSpinBox = QDoubleSpinBox(self.tab_3)
        self.BaselineTemperatureSpinBox.setObjectName(u"BaselineTemperatureSpinBox")
        self.BaselineTemperatureSpinBox.setGeometry(QRect(343, 30, 61, 22))
        self.BaselineTemperatureSpinBox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.BaselineTemperatureSpinBox.setDecimals(1)
        self.BaselineTemperatureSpinBox.setMinimum(35.500000000000000)
        self.BaselineTemperatureSpinBox.setMaximum(38.000000000000000)
        self.BaselineTemperatureSpinBox.setSingleStep(0.100000000000000)
        self.BaselineTemperatureSpinBox.setValue(37.000000000000000)
        self.FocalLengthLabel_7 = QLabel(self.tab_3)
        self.FocalLengthLabel_7.setObjectName(u"FocalLengthLabel_7")
        self.FocalLengthLabel_7.setGeometry(QRect(170, 30, 171, 20))
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.CancelpushButton.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.ContinuepushButton.setText(QCoreApplication.translate("Dialog", u"Ok", None))
        self.ResetpushButton.setText(QCoreApplication.translate("Dialog", u"Reset to defaults", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Elastix co-registration Optimizer", None))
        self.ElastixOptimizercomboBox.setItemText(0, QCoreApplication.translate("Dialog", u"AdaptiveStochasticGradientDescent", None))
        self.ElastixOptimizercomboBox.setItemText(1, QCoreApplication.translate("Dialog", u"FiniteDifferenceGradientDescent", None))
        self.ElastixOptimizercomboBox.setItemText(2, QCoreApplication.translate("Dialog", u"QuasiNewtonLBFGS", None))

        self.ForceBlendercheckBox.setText(QCoreApplication.translate("Dialog", u"Force using Blender for Constructive Solid Geometry   ", None))
        self.FocalLengthLabel_3.setText(QCoreApplication.translate("Dialog", u" (applicable using only MRI input)", None))
        self.grpManualFOV.setTitle("")
        self.DiameterLabel.setText(QCoreApplication.translate("Dialog", u"Length (mm)", None))
        self.FocalLengthLabel.setText(QCoreApplication.translate("Dialog", u"Diameter (mm)", None))
        self.ManualFOVcheckBox.setText(QCoreApplication.translate("Dialog", u"Manual Subvolume  ", None))
        self.FocalLengthLabel_2.setText(QCoreApplication.translate("Dialog", u"Proportion of trabecular bone", None))
        self.InvertZTEcheckBox.setText(QCoreApplication.translate("Dialog", u"Invert ZTE", None))
        self.DisableCTMedianFiltercheckBox.setText(QCoreApplication.translate("Dialog", u"Disable median filter in CT/ZTE/PETRA", None))
        self.FocalLengthLabel_4.setText(QCoreApplication.translate("Dialog", u"PETRA: Number of peaks", None))
        self.FocalLengthLabel_5.setText(QCoreApplication.translate("Dialog", u"PETRA: Minimal distance between peaks", None))
        self.GeneratePETRAHistogramcheckBox.setText(QCoreApplication.translate("Dialog", u"PETRA: Generate histogram plot ", None))
        self.FocalLengthLabel_6.setText(QCoreApplication.translate("Dialog", u" (Plot saved at same location as PETRA Nifti)", None))
        self.FocalLengthLabel_8.setText(QCoreApplication.translate("Dialog", u"ZTE Conversion  (m* ZTE   + c).  Slope m:", None))
        self.FocalLengthLabel_9.setText(QCoreApplication.translate("Dialog", u"Offset c", None))
        self.FocalLengthLabel_10.setText(QCoreApplication.translate("Dialog", u"PETRA Conversion  (m* PETRA   + c).  Slope m:", None))
        self.FocalLengthLabel_11.setText(QCoreApplication.translate("Dialog", u"Offset c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Domain Generation", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"CTX-500 Correction", None))
        self.CTX500CorrectioncomboBox.setItemText(0, QCoreApplication.translate("Dialog", u"Original", None))
        self.CTX500CorrectioncomboBox.setItemText(1, QCoreApplication.translate("Dialog", u"July2024", None))

        self.SaveStresscheckBox.setText(QCoreApplication.translate("Dialog", u"Save stress data  ", None))
        self.SaveDisplacementcheckBox.setText(QCoreApplication.translate("Dialog", u"Save particle displacement data  ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Transcranial Ultrasound", None))
        self.FocalLengthLabel_7.setText(QCoreApplication.translate("Dialog", u"Baseline temperature (\u00b0C)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Thermal", None))
    # retranslateUi

