# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QDoubleSpinBox, QFrame, QGroupBox, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QSpinBox,
    QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(664, 516)
        self.CancelpushButton = QPushButton(Dialog)
        self.CancelpushButton.setObjectName(u"CancelpushButton")
        self.CancelpushButton.setGeometry(QRect(580, 479, 74, 32))
        self.ContinuepushButton = QPushButton(Dialog)
        self.ContinuepushButton.setObjectName(u"ContinuepushButton")
        self.ContinuepushButton.setGeometry(QRect(276, 481, 136, 32))
        self.ResetpushButton = QPushButton(Dialog)
        self.ResetpushButton.setObjectName(u"ResetpushButton")
        self.ResetpushButton.setGeometry(QRect(6, 479, 136, 32))
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(5, 4, 644, 474))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(16, 11, 201, 16))
        self.ElastixOptimizercomboBox = QComboBox(self.tab)
        self.ElastixOptimizercomboBox.addItem("")
        self.ElastixOptimizercomboBox.addItem("")
        self.ElastixOptimizercomboBox.addItem("")
        self.ElastixOptimizercomboBox.setObjectName(u"ElastixOptimizercomboBox")
        self.ElastixOptimizercomboBox.setGeometry(QRect(208, 5, 281, 30))
        self.ElastixOptimizercomboBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ElastixOptimizercomboBox.setStyleSheet(u"")
        self.ForceBlendercheckBox = QCheckBox(self.tab)
        self.ForceBlendercheckBox.setObjectName(u"ForceBlendercheckBox")
        self.ForceBlendercheckBox.setGeometry(QRect(9, 107, 349, 20))
        self.ForceBlendercheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.TrabecularProportionSpinBox = QDoubleSpinBox(self.tab)
        self.TrabecularProportionSpinBox.setObjectName(u"TrabecularProportionSpinBox")
        self.TrabecularProportionSpinBox.setGeometry(QRect(201, 35, 61, 22))
        self.TrabecularProportionSpinBox.setDecimals(1)
        self.TrabecularProportionSpinBox.setMinimum(0.000000000000000)
        self.TrabecularProportionSpinBox.setMaximum(1.000000000000000)
        self.TrabecularProportionSpinBox.setSingleStep(0.100000000000000)
        self.TrabecularProportionSpinBox.setValue(1.000000000000000)
        self.FocalLengthLabel_3 = QLabel(self.tab)
        self.FocalLengthLabel_3.setObjectName(u"FocalLengthLabel_3")
        self.FocalLengthLabel_3.setGeometry(QRect(268, 36, 251, 20))
        self.grpManualFOV = QGroupBox(self.tab)
        self.grpManualFOV.setObjectName(u"grpManualFOV")
        self.grpManualFOV.setEnabled(False)
        self.grpManualFOV.setGeometry(QRect(233, 157, 206, 72))
        self.FOVDiameterSpinBox = QDoubleSpinBox(self.grpManualFOV)
        self.FOVDiameterSpinBox.setObjectName(u"FOVDiameterSpinBox")
        self.FOVDiameterSpinBox.setGeometry(QRect(105, 7, 90, 22))
        self.FOVDiameterSpinBox.setDecimals(1)
        self.FOVDiameterSpinBox.setMinimum(10.000000000000000)
        self.FOVDiameterSpinBox.setMaximum(400.000000000000000)
        self.FOVDiameterSpinBox.setSingleStep(0.100000000000000)
        self.FOVDiameterSpinBox.setValue(200.000000000000000)
        self.DiameterLabel = QLabel(self.grpManualFOV)
        self.DiameterLabel.setObjectName(u"DiameterLabel")
        self.DiameterLabel.setGeometry(QRect(9, 40, 82, 20))
        self.FOVLengthSpinBox = QDoubleSpinBox(self.grpManualFOV)
        self.FOVLengthSpinBox.setObjectName(u"FOVLengthSpinBox")
        self.FOVLengthSpinBox.setGeometry(QRect(105, 40, 90, 22))
        self.FOVLengthSpinBox.setDecimals(1)
        self.FOVLengthSpinBox.setMinimum(200.000000000000000)
        self.FOVLengthSpinBox.setMaximum(600.000000000000000)
        self.FOVLengthSpinBox.setSingleStep(0.100000000000000)
        self.FOVLengthSpinBox.setValue(400.000000000000000)
        self.FocalLengthLabel = QLabel(self.grpManualFOV)
        self.FocalLengthLabel.setObjectName(u"FocalLengthLabel")
        self.FocalLengthLabel.setGeometry(QRect(9, 7, 94, 20))
        self.ManualFOVcheckBox = QCheckBox(self.tab)
        self.ManualFOVcheckBox.setObjectName(u"ManualFOVcheckBox")
        self.ManualFOVcheckBox.setGeometry(QRect(9, 131, 150, 20))
        self.ManualFOVcheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.FocalLengthLabel_2 = QLabel(self.tab)
        self.FocalLengthLabel_2.setObjectName(u"FocalLengthLabel_2")
        self.FocalLengthLabel_2.setGeometry(QRect(15, 34, 181, 20))
        self.InvertZTEcheckBox = QCheckBox(self.tab)
        self.InvertZTEcheckBox.setObjectName(u"InvertZTEcheckBox")
        self.InvertZTEcheckBox.setGeometry(QRect(13, 233, 150, 20))
        self.InvertZTEcheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.DisableCTMedianFiltercheckBox = QCheckBox(self.tab)
        self.DisableCTMedianFiltercheckBox.setObjectName(u"DisableCTMedianFiltercheckBox")
        self.DisableCTMedianFiltercheckBox.setGeometry(QRect(13, 259, 251, 20))
        self.DisableCTMedianFiltercheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.FocalLengthLabel_4 = QLabel(self.tab)
        self.FocalLengthLabel_4.setObjectName(u"FocalLengthLabel_4")
        self.FocalLengthLabel_4.setGeometry(QRect(18, 282, 156, 20))
        self.FocalLengthLabel_5 = QLabel(self.tab)
        self.FocalLengthLabel_5.setObjectName(u"FocalLengthLabel_5")
        self.FocalLengthLabel_5.setGeometry(QRect(17, 308, 241, 20))
        self.GeneratePETRAHistogramcheckBox = QCheckBox(self.tab)
        self.GeneratePETRAHistogramcheckBox.setObjectName(u"GeneratePETRAHistogramcheckBox")
        self.GeneratePETRAHistogramcheckBox.setGeometry(QRect(16, 334, 251, 20))
        self.GeneratePETRAHistogramcheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.FocalLengthLabel_6 = QLabel(self.tab)
        self.FocalLengthLabel_6.setObjectName(u"FocalLengthLabel_6")
        self.FocalLengthLabel_6.setGeometry(QRect(273, 334, 276, 20))
        self.PetraNPeaksSpinBox = QSpinBox(self.tab)
        self.PetraNPeaksSpinBox.setObjectName(u"PetraNPeaksSpinBox")
        self.PetraNPeaksSpinBox.setGeometry(QRect(175, 282, 42, 21))
        self.PetraNPeaksSpinBox.setMinimum(2)
        self.PetraNPeaksSpinBox.setMaximum(50)
        self.PetraMRIPeakDistancespinBox = QSpinBox(self.tab)
        self.PetraMRIPeakDistancespinBox.setObjectName(u"PetraMRIPeakDistancespinBox")
        self.PetraMRIPeakDistancespinBox.setGeometry(QRect(261, 308, 42, 22))
        self.PetraMRIPeakDistancespinBox.setMinimum(10)
        self.PetraMRIPeakDistancespinBox.setMaximum(5000)
        self.PetraMRIPeakDistancespinBox.setValue(50)
        self.ZTESlopeSpinBox = QDoubleSpinBox(self.tab)
        self.ZTESlopeSpinBox.setObjectName(u"ZTESlopeSpinBox")
        self.ZTESlopeSpinBox.setGeometry(QRect(309, 358, 86, 22))
        self.ZTESlopeSpinBox.setDecimals(1)
        self.ZTESlopeSpinBox.setMinimum(-5000.000000000000000)
        self.ZTESlopeSpinBox.setMaximum(5000.000000000000000)
        self.ZTESlopeSpinBox.setSingleStep(10.000000000000000)
        self.ZTESlopeSpinBox.setValue(-2000.000000000000000)
        self.FocalLengthLabel_8 = QLabel(self.tab)
        self.FocalLengthLabel_8.setObjectName(u"FocalLengthLabel_8")
        self.FocalLengthLabel_8.setGeometry(QRect(53, 358, 255, 20))
        self.ZTEOffsetSpinBox = QDoubleSpinBox(self.tab)
        self.ZTEOffsetSpinBox.setObjectName(u"ZTEOffsetSpinBox")
        self.ZTEOffsetSpinBox.setGeometry(QRect(479, 358, 86, 22))
        self.ZTEOffsetSpinBox.setDecimals(1)
        self.ZTEOffsetSpinBox.setMinimum(-5000.000000000000000)
        self.ZTEOffsetSpinBox.setMaximum(5000.000000000000000)
        self.ZTEOffsetSpinBox.setSingleStep(10.000000000000000)
        self.ZTEOffsetSpinBox.setValue(-2000.000000000000000)
        self.FocalLengthLabel_9 = QLabel(self.tab)
        self.FocalLengthLabel_9.setObjectName(u"FocalLengthLabel_9")
        self.FocalLengthLabel_9.setGeometry(QRect(419, 358, 70, 20))
        self.PETRASlopeSpinBox = QDoubleSpinBox(self.tab)
        self.PETRASlopeSpinBox.setObjectName(u"PETRASlopeSpinBox")
        self.PETRASlopeSpinBox.setGeometry(QRect(309, 382, 86, 22))
        self.PETRASlopeSpinBox.setDecimals(1)
        self.PETRASlopeSpinBox.setMinimum(-5000.000000000000000)
        self.PETRASlopeSpinBox.setMaximum(5000.000000000000000)
        self.PETRASlopeSpinBox.setSingleStep(10.000000000000000)
        self.PETRASlopeSpinBox.setValue(-2000.000000000000000)
        self.PETRAOffsetSpinBox = QDoubleSpinBox(self.tab)
        self.PETRAOffsetSpinBox.setObjectName(u"PETRAOffsetSpinBox")
        self.PETRAOffsetSpinBox.setGeometry(QRect(479, 382, 86, 22))
        self.PETRAOffsetSpinBox.setDecimals(1)
        self.PETRAOffsetSpinBox.setMinimum(-5000.000000000000000)
        self.PETRAOffsetSpinBox.setMaximum(5000.000000000000000)
        self.PETRAOffsetSpinBox.setSingleStep(10.000000000000000)
        self.PETRAOffsetSpinBox.setValue(-2000.000000000000000)
        self.FocalLengthLabel_10 = QLabel(self.tab)
        self.FocalLengthLabel_10.setObjectName(u"FocalLengthLabel_10")
        self.FocalLengthLabel_10.setGeometry(QRect(20, 382, 288, 20))
        self.FocalLengthLabel_11 = QLabel(self.tab)
        self.FocalLengthLabel_11.setObjectName(u"FocalLengthLabel_11")
        self.FocalLengthLabel_11.setGeometry(QRect(419, 382, 70, 20))
        self.SegmentBrainTissuecheckBox = QCheckBox(self.tab)
        self.SegmentBrainTissuecheckBox.setObjectName(u"SegmentBrainTissuecheckBox")
        self.SegmentBrainTissuecheckBox.setGeometry(QRect(9, 56, 343, 20))
        self.SegmentBrainTissuecheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.SimbNINBSRootlineEdit = QLineEdit(self.tab)
        self.SimbNINBSRootlineEdit.setObjectName(u"SimbNINBSRootlineEdit")
        self.SimbNINBSRootlineEdit.setGeometry(QRect(142, 80, 485, 21))
        self.SimbNINBSRootlineEdit.setStyleSheet(u"")
        self.SimNIBSRootpushButton = QPushButton(self.tab)
        self.SimNIBSRootpushButton.setObjectName(u"SimNIBSRootpushButton")
        self.SimNIBSRootpushButton.setGeometry(QRect(9, 75, 120, 32))
        self.SimNIBSRootpushButton.setStyleSheet(u"")
        self.SimNIBSRootpushButton.setAutoDefault(False)
        self.SimNIBSRootpushButton.setFlat(False)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.SaveStresscheckBox = QCheckBox(self.tab_2)
        self.SaveStresscheckBox.setObjectName(u"SaveStresscheckBox")
        self.SaveStresscheckBox.setGeometry(QRect(122, 13, 149, 20))
        self.SaveStresscheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.SaveDisplacementcheckBox = QCheckBox(self.tab_2)
        self.SaveDisplacementcheckBox.setObjectName(u"SaveDisplacementcheckBox")
        self.SaveDisplacementcheckBox.setGeometry(QRect(322, 14, 228, 20))
        self.SaveDisplacementcheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.frame = QFrame(self.tab_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(11, 41, 615, 68))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.TxOptimizedWeightspushButton = QPushButton(self.frame)
        self.TxOptimizedWeightspushButton.setObjectName(u"TxOptimizedWeightspushButton")
        self.TxOptimizedWeightspushButton.setGeometry(QRect(6, 30, 120, 32))
        self.TxOptimizedWeightspushButton.setStyleSheet(u"")
        self.TxOptimizedWeightspushButton.setAutoDefault(False)
        self.TxOptimizedWeightspushButton.setFlat(False)
        self.TxOptimizedWeightsLineEdit = QLineEdit(self.frame)
        self.TxOptimizedWeightsLineEdit.setObjectName(u"TxOptimizedWeightsLineEdit")
        self.TxOptimizedWeightsLineEdit.setGeometry(QRect(139, 35, 469, 21))
        self.TxOptimizedWeightsLineEdit.setStyleSheet(u"")
        self.TxWeightLabel = QLabel(self.frame)
        self.TxWeightLabel.setObjectName(u"TxWeightLabel")
        self.TxWeightLabel.setGeometry(QRect(122, 8, 340, 20))
        self.frame_2 = QFrame(self.tab_2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 117, 615, 325))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.TxWeightLabel_4 = QLabel(self.frame_2)
        self.TxWeightLabel_4.setObjectName(u"TxWeightLabel_4")
        self.TxWeightLabel_4.setGeometry(QRect(226, 8, 135, 16))
        self.TxOptimizedWeightspushButton_4 = QPushButton(self.frame_2)
        self.TxOptimizedWeightspushButton_4.setObjectName(u"TxOptimizedWeightspushButton_4")
        self.TxOptimizedWeightspushButton_4.setGeometry(QRect(7, 18, 118, 47))
        self.TxOptimizedWeightspushButton_4.setStyleSheet(u"")
        self.TxOptimizedWeightspushButton_4.setAutoDefault(False)
        self.TxOptimizedWeightspushButton_4.setFlat(False)
        self.ExcelAcousticProfilesLineEdit = QLineEdit(self.frame_2)
        self.ExcelAcousticProfilesLineEdit.setObjectName(u"ExcelAcousticProfilesLineEdit")
        self.ExcelAcousticProfilesLineEdit.setGeometry(QRect(139, 31, 469, 21))
        self.ExcelAcousticProfilesLineEdit.setStyleSheet(u"")
        self.TxOptimizedWeightspushButton_5 = QPushButton(self.frame_2)
        self.TxOptimizedWeightspushButton_5.setObjectName(u"TxOptimizedWeightspushButton_5")
        self.TxOptimizedWeightspushButton_5.setGeometry(QRect(5, 225, 118, 48))
        self.TxOptimizedWeightspushButton_5.setStyleSheet(u"")
        self.TxOptimizedWeightspushButton_5.setAutoDefault(False)
        self.TxOptimizedWeightspushButton_5.setFlat(False)
        self.TxOptimizedWeightsLineEdit_5 = QLineEdit(self.frame_2)
        self.TxOptimizedWeightsLineEdit_5.setObjectName(u"TxOptimizedWeightsLineEdit_5")
        self.TxOptimizedWeightsLineEdit_5.setGeometry(QRect(142, 238, 464, 21))
        self.TxOptimizedWeightsLineEdit_5.setStyleSheet(u"")
        self.ProfilesCellRangeLineEdit = QLineEdit(self.frame_2)
        self.ProfilesCellRangeLineEdit.setObjectName(u"ProfilesCellRangeLineEdit")
        self.ProfilesCellRangeLineEdit.setGeometry(QRect(141, 78, 127, 21))
        self.ProfilesCellRangeLineEdit.setStyleSheet(u"")
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(11, 74, 115, 29))
        self.TxOptimizedWeightspushButton_6 = QPushButton(self.frame_2)
        self.TxOptimizedWeightspushButton_6.setObjectName(u"TxOptimizedWeightspushButton_6")
        self.TxOptimizedWeightspushButton_6.setGeometry(QRect(7, 133, 118, 47))
        self.TxOptimizedWeightspushButton_6.setStyleSheet(u"")
        self.TxOptimizedWeightspushButton_6.setAutoDefault(False)
        self.TxOptimizedWeightspushButton_6.setFlat(False)
        self.PhaseCellRangeLineEdit = QLineEdit(self.frame_2)
        self.PhaseCellRangeLineEdit.setObjectName(u"PhaseCellRangeLineEdit")
        self.PhaseCellRangeLineEdit.setGeometry(QRect(141, 193, 127, 21))
        self.PhaseCellRangeLineEdit.setStyleSheet(u"")
        self.ExcelPhaseProgrammingLineEdit = QLineEdit(self.frame_2)
        self.ExcelPhaseProgrammingLineEdit.setObjectName(u"ExcelPhaseProgrammingLineEdit")
        self.ExcelPhaseProgrammingLineEdit.setGeometry(QRect(139, 146, 469, 21))
        self.ExcelPhaseProgrammingLineEdit.setStyleSheet(u"")
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(11, 189, 115, 29))
        self.UsePhaseFilecheckBox = QCheckBox(self.frame_2)
        self.UsePhaseFilecheckBox.setObjectName(u"UsePhaseFilecheckBox")
        self.UsePhaseFilecheckBox.setGeometry(QRect(216, 111, 211, 20))
        self.UsePhaseFilecheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ContinuepushButton_2 = QPushButton(self.frame_2)
        self.ContinuepushButton_2.setObjectName(u"ContinuepushButton_2")
        self.ContinuepushButton_2.setGeometry(QRect(291, 280, 161, 32))
        self.ContinuepushButton_2.setStyleSheet(u"background-color: rgb(255, 131, 119);")
        self.FocalLengthLabel_23 = QLabel(self.frame_2)
        self.FocalLengthLabel_23.setObjectName(u"FocalLengthLabel_23")
        self.FocalLengthLabel_23.setGeometry(QRect(21, 279, 171, 33))
        self.LambdaLineEdit = QLineEdit(self.frame_2)
        self.LambdaLineEdit.setObjectName(u"LambdaLineEdit")
        self.LambdaLineEdit.setGeometry(QRect(185, 284, 85, 21))
        self.LambdaLineEdit.setStyleSheet(u"")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.BaselineTemperatureSpinBox = QDoubleSpinBox(self.tab_3)
        self.BaselineTemperatureSpinBox.setObjectName(u"BaselineTemperatureSpinBox")
        self.BaselineTemperatureSpinBox.setGeometry(QRect(343, 30, 61, 22))
        self.BaselineTemperatureSpinBox.setDecimals(1)
        self.BaselineTemperatureSpinBox.setMinimum(35.500000000000000)
        self.BaselineTemperatureSpinBox.setMaximum(38.000000000000000)
        self.BaselineTemperatureSpinBox.setSingleStep(0.100000000000000)
        self.BaselineTemperatureSpinBox.setValue(37.000000000000000)
        self.FocalLengthLabel_7 = QLabel(self.tab_3)
        self.FocalLengthLabel_7.setObjectName(u"FocalLengthLabel_7")
        self.FocalLengthLabel_7.setGeometry(QRect(170, 30, 171, 20))
        self.LimitBHTEIterationsPerProcessSpinBox = QSpinBox(self.tab_3)
        self.LimitBHTEIterationsPerProcessSpinBox.setObjectName(u"LimitBHTEIterationsPerProcessSpinBox")
        self.LimitBHTEIterationsPerProcessSpinBox.setGeometry(QRect(346, 61, 59, 22))
        self.LimitBHTEIterationsPerProcessSpinBox.setMinimum(5)
        self.LimitBHTEIterationsPerProcessSpinBox.setMaximum(200)
        self.LimitBHTEIterationsPerProcessSpinBox.setValue(100)
        self.FocalLengthLabel_12 = QLabel(self.tab_3)
        self.FocalLengthLabel_12.setObjectName(u"FocalLengthLabel_12")
        self.FocalLengthLabel_12.setGeometry(QRect(81, 59, 248, 28))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.bForceHomogenousMediumcheckBox = QCheckBox(self.tab_4)
        self.bForceHomogenousMediumcheckBox.setObjectName(u"bForceHomogenousMediumcheckBox")
        self.bForceHomogenousMediumcheckBox.setGeometry(QRect(176, 12, 192, 20))
        self.bForceHomogenousMediumcheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.FocalLengthLabel_13 = QLabel(self.tab_4)
        self.FocalLengthLabel_13.setObjectName(u"FocalLengthLabel_13")
        self.FocalLengthLabel_13.setGeometry(QRect(132, 39, 52, 28))
        self.HomogenousDensitySpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousDensitySpinBox.setObjectName(u"HomogenousDensitySpinBox")
        self.HomogenousDensitySpinBox.setGeometry(QRect(129, 70, 67, 22))
        self.HomogenousDensitySpinBox.setDecimals(1)
        self.HomogenousDensitySpinBox.setMinimum(800.000000000000000)
        self.HomogenousDensitySpinBox.setMaximum(3000.000000000000000)
        self.HomogenousDensitySpinBox.setSingleStep(1.000000000000000)
        self.HomogenousDensitySpinBox.setValue(1000.000000000000000)
        self.FocalLengthLabel_14 = QLabel(self.tab_4)
        self.FocalLengthLabel_14.setObjectName(u"FocalLengthLabel_14")
        self.FocalLengthLabel_14.setGeometry(QRect(194, 40, 52, 28))
        self.HomogenousLSoSSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousLSoSSpinBox.setObjectName(u"HomogenousLSoSSpinBox")
        self.HomogenousLSoSSpinBox.setGeometry(QRect(204, 70, 67, 22))
        self.HomogenousLSoSSpinBox.setDecimals(1)
        self.HomogenousLSoSSpinBox.setMinimum(1000.000000000000000)
        self.HomogenousLSoSSpinBox.setMaximum(3000.000000000000000)
        self.HomogenousLSoSSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousLSoSSpinBox.setValue(1500.000000000000000)
        self.HomogenousSSoSSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousSSoSSpinBox.setObjectName(u"HomogenousSSoSSpinBox")
        self.HomogenousSSoSSpinBox.setGeometry(QRect(355, 70, 67, 22))
        self.HomogenousSSoSSpinBox.setDecimals(1)
        self.HomogenousSSoSSpinBox.setMinimum(0.000000000000000)
        self.HomogenousSSoSSpinBox.setMaximum(3000.000000000000000)
        self.HomogenousSSoSSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousSSoSSpinBox.setValue(0.000000000000000)
        self.FocalLengthLabel_15 = QLabel(self.tab_4)
        self.FocalLengthLabel_15.setObjectName(u"FocalLengthLabel_15")
        self.FocalLengthLabel_15.setGeometry(QRect(277, 39, 52, 28))
        self.FocalLengthLabel_16 = QLabel(self.tab_4)
        self.FocalLengthLabel_16.setObjectName(u"FocalLengthLabel_16")
        self.FocalLengthLabel_16.setGeometry(QRect(346, 40, 52, 28))
        self.HomogenousLAttSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousLAttSpinBox.setObjectName(u"HomogenousLAttSpinBox")
        self.HomogenousLAttSpinBox.setGeometry(QRect(280, 70, 67, 22))
        self.HomogenousLAttSpinBox.setDecimals(1)
        self.HomogenousLAttSpinBox.setMinimum(0.000000000000000)
        self.HomogenousLAttSpinBox.setMaximum(200.000000000000000)
        self.HomogenousLAttSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousLAttSpinBox.setValue(5.000000000000000)
        self.HomogenousSAttSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousSAttSpinBox.setObjectName(u"HomogenousSAttSpinBox")
        self.HomogenousSAttSpinBox.setGeometry(QRect(437, 70, 67, 22))
        self.HomogenousSAttSpinBox.setDecimals(1)
        self.HomogenousSAttSpinBox.setMinimum(0.000000000000000)
        self.HomogenousSAttSpinBox.setMaximum(500.000000000000000)
        self.HomogenousSAttSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousSAttSpinBox.setValue(0.000000000000000)
        self.FocalLengthLabel_17 = QLabel(self.tab_4)
        self.FocalLengthLabel_17.setObjectName(u"FocalLengthLabel_17")
        self.FocalLengthLabel_17.setGeometry(QRect(427, 39, 52, 28))
        self.HomogenousPerfusionSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousPerfusionSpinBox.setObjectName(u"HomogenousPerfusionSpinBox")
        self.HomogenousPerfusionSpinBox.setGeometry(QRect(280, 124, 67, 22))
        self.HomogenousPerfusionSpinBox.setDecimals(1)
        self.HomogenousPerfusionSpinBox.setMinimum(0.000000000000000)
        self.HomogenousPerfusionSpinBox.setMaximum(4000.000000000000000)
        self.HomogenousPerfusionSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousPerfusionSpinBox.setValue(550.000000000000000)
        self.FocalLengthLabel_18 = QLabel(self.tab_4)
        self.FocalLengthLabel_18.setObjectName(u"FocalLengthLabel_18")
        self.FocalLengthLabel_18.setGeometry(QRect(110, 93, 69, 28))
        self.HomogenousThermCondSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousThermCondSpinBox.setObjectName(u"HomogenousThermCondSpinBox")
        self.HomogenousThermCondSpinBox.setGeometry(QRect(204, 124, 67, 22))
        self.HomogenousThermCondSpinBox.setDecimals(2)
        self.HomogenousThermCondSpinBox.setMinimum(0.000000000000000)
        self.HomogenousThermCondSpinBox.setMaximum(3.000000000000000)
        self.HomogenousThermCondSpinBox.setSingleStep(0.010000000000000)
        self.HomogenousThermCondSpinBox.setValue(0.500000000000000)
        self.HomogenousAbsorptionSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousAbsorptionSpinBox.setObjectName(u"HomogenousAbsorptionSpinBox")
        self.HomogenousAbsorptionSpinBox.setGeometry(QRect(355, 124, 67, 22))
        self.HomogenousAbsorptionSpinBox.setDecimals(2)
        self.HomogenousAbsorptionSpinBox.setMinimum(0.000000000000000)
        self.HomogenousAbsorptionSpinBox.setMaximum(1.000000000000000)
        self.HomogenousAbsorptionSpinBox.setSingleStep(0.010000000000000)
        self.HomogenousAbsorptionSpinBox.setValue(0.850000000000000)
        self.HomogenousInitTempSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousInitTempSpinBox.setObjectName(u"HomogenousInitTempSpinBox")
        self.HomogenousInitTempSpinBox.setGeometry(QRect(437, 124, 67, 22))
        self.HomogenousInitTempSpinBox.setDecimals(1)
        self.HomogenousInitTempSpinBox.setMinimum(0.000000000000000)
        self.HomogenousInitTempSpinBox.setMaximum(60.000000000000000)
        self.HomogenousInitTempSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousInitTempSpinBox.setValue(37.000000000000000)
        self.FocalLengthLabel_19 = QLabel(self.tab_4)
        self.FocalLengthLabel_19.setObjectName(u"FocalLengthLabel_19")
        self.FocalLengthLabel_19.setGeometry(QRect(277, 93, 61, 28))
        self.FocalLengthLabel_20 = QLabel(self.tab_4)
        self.FocalLengthLabel_20.setObjectName(u"FocalLengthLabel_20")
        self.FocalLengthLabel_20.setGeometry(QRect(350, 94, 52, 28))
        self.FocalLengthLabel_21 = QLabel(self.tab_4)
        self.FocalLengthLabel_21.setObjectName(u"FocalLengthLabel_21")
        self.FocalLengthLabel_21.setGeometry(QRect(200, 94, 54, 28))
        self.HomogenousSpecHeatSpinBox = QDoubleSpinBox(self.tab_4)
        self.HomogenousSpecHeatSpinBox.setObjectName(u"HomogenousSpecHeatSpinBox")
        self.HomogenousSpecHeatSpinBox.setGeometry(QRect(129, 124, 67, 22))
        self.HomogenousSpecHeatSpinBox.setDecimals(1)
        self.HomogenousSpecHeatSpinBox.setMinimum(2000.000000000000000)
        self.HomogenousSpecHeatSpinBox.setMaximum(6000.000000000000000)
        self.HomogenousSpecHeatSpinBox.setSingleStep(1.000000000000000)
        self.HomogenousSpecHeatSpinBox.setValue(3583.000000000000000)
        self.FocalLengthLabel_22 = QLabel(self.tab_4)
        self.FocalLengthLabel_22.setObjectName(u"FocalLengthLabel_22")
        self.FocalLengthLabel_22.setGeometry(QRect(427, 93, 63, 28))
        self.bForceNoAbsorptionSkullScalpcheckBox = QCheckBox(self.tab_4)
        self.bForceNoAbsorptionSkullScalpcheckBox.setObjectName(u"bForceNoAbsorptionSkullScalpcheckBox")
        self.bForceNoAbsorptionSkullScalpcheckBox.setGeometry(QRect(177, 168, 264, 20))
        self.bForceNoAbsorptionSkullScalpcheckBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.CancelpushButton.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.ContinuepushButton.setText(QCoreApplication.translate("Dialog", u"Ok", None))
        self.ResetpushButton.setText(QCoreApplication.translate("Dialog", u"Reset to defaults", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Elastix co-registration Optimizer", None))
        self.ElastixOptimizercomboBox.setItemText(0, QCoreApplication.translate("Dialog", u"AdaptiveStochasticGradientDescent", None))
        self.ElastixOptimizercomboBox.setItemText(1, QCoreApplication.translate("Dialog", u"FiniteDifferenceGradientDescent", None))
        self.ElastixOptimizercomboBox.setItemText(2, QCoreApplication.translate("Dialog", u"QuasiNewtonLBFGS", None))

        self.ForceBlendercheckBox.setText(QCoreApplication.translate("Dialog", u"Force using Blender for Constructive Solid Geometry   ", None))
        self.FocalLengthLabel_3.setText(QCoreApplication.translate("Dialog", u" (applicable using only MRI input)", None))
        self.grpManualFOV.setTitle("")
        self.DiameterLabel.setText(QCoreApplication.translate("Dialog", u"Length (mm)", None))
        self.FocalLengthLabel.setText(QCoreApplication.translate("Dialog", u"Diameter (mm)", None))
        self.ManualFOVcheckBox.setText(QCoreApplication.translate("Dialog", u"Manual Subvolume  ", None))
        self.FocalLengthLabel_2.setText(QCoreApplication.translate("Dialog", u"Proportion of trabecular bone", None))
        self.InvertZTEcheckBox.setText(QCoreApplication.translate("Dialog", u"Invert ZTE", None))
        self.DisableCTMedianFiltercheckBox.setText(QCoreApplication.translate("Dialog", u"Disable median filter in CT/ZTE/PETRA", None))
        self.FocalLengthLabel_4.setText(QCoreApplication.translate("Dialog", u"PETRA: Number of peaks", None))
        self.FocalLengthLabel_5.setText(QCoreApplication.translate("Dialog", u"PETRA: Minimal distance between peaks", None))
        self.GeneratePETRAHistogramcheckBox.setText(QCoreApplication.translate("Dialog", u"PETRA: Generate histogram plot ", None))
        self.FocalLengthLabel_6.setText(QCoreApplication.translate("Dialog", u" (Plot saved at same location as PETRA Nifti)", None))
        self.FocalLengthLabel_8.setText(QCoreApplication.translate("Dialog", u"ZTE Conversion  (m* ZTE   + c).  Slope m:", None))
        self.FocalLengthLabel_9.setText(QCoreApplication.translate("Dialog", u"Offset c", None))
        self.FocalLengthLabel_10.setText(QCoreApplication.translate("Dialog", u"PETRA Conversion  (m* PETRA   + c).  Slope m:", None))
        self.FocalLengthLabel_11.setText(QCoreApplication.translate("Dialog", u"Offset c", None))
        self.SegmentBrainTissuecheckBox.setText(QCoreApplication.translate("Dialog", u"Segment white matter, gray matter and CSF", None))
        self.SimbNINBSRootlineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.SimNIBSRootpushButton.setText(QCoreApplication.translate("Dialog", u"SimNIBS root...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Domain Generation", None))
        self.SaveStresscheckBox.setText(QCoreApplication.translate("Dialog", u"Save stress data  ", None))
        self.SaveDisplacementcheckBox.setText(QCoreApplication.translate("Dialog", u"Save particle displacement data  ", None))
        self.TxOptimizedWeightspushButton.setText(QCoreApplication.translate("Dialog", u"Calibration file...", None))
        self.TxOptimizedWeightsLineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.TxWeightLabel.setText(QCoreApplication.translate("Dialog", u"Transducer : ", None))
        self.TxWeightLabel_4.setText(QCoreApplication.translate("Dialog", u"Calibration Execution ", None))
        self.TxOptimizedWeightspushButton_4.setText(QCoreApplication.translate("Dialog", u"Excel acoustic\n"
"profiles file...", None))
        self.ExcelAcousticProfilesLineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.TxOptimizedWeightspushButton_5.setText(QCoreApplication.translate("Dialog", u"Results path...", None))
        self.TxOptimizedWeightsLineEdit_5.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.ProfilesCellRangeLineEdit.setText("")
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Cell range\n"
"(i.e, A1:Z90)", None))
        self.TxOptimizedWeightspushButton_6.setText(QCoreApplication.translate("Dialog", u"Excel phase file...", None))
        self.PhaseCellRangeLineEdit.setText("")
        self.ExcelPhaseProgrammingLineEdit.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Cell range\n"
"(i.e, A1:Z90)", None))
        self.UsePhaseFilecheckBox.setText(QCoreApplication.translate("Dialog", u"Use manufacuterer phase data", None))
        self.ContinuepushButton_2.setText(QCoreApplication.translate("Dialog", u"Execute - BE PATIENT!", None))
        self.FocalLengthLabel_23.setText(QCoreApplication.translate("Dialog", u"Lamba coefficient\n"
"(between 1e-5 and 1e-3)", None))
        self.LambdaLineEdit.setText(QCoreApplication.translate("Dialog", u"1e-4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Transcranial Ultrasound", None))
        self.FocalLengthLabel_7.setText(QCoreApplication.translate("Dialog", u"Baseline temperature (\u00b0C)", None))
        self.FocalLengthLabel_12.setText(QCoreApplication.translate("Dialog", u"Threshold for # of process\n"
"for large thermal simulation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Thermal", None))
        self.bForceHomogenousMediumcheckBox.setText(QCoreApplication.translate("Dialog", u"Force homogenous medium", None))
        self.FocalLengthLabel_13.setText(QCoreApplication.translate("Dialog", u"Density", None))
        self.FocalLengthLabel_14.setText(QCoreApplication.translate("Dialog", u"LSoS", None))
        self.FocalLengthLabel_15.setText(QCoreApplication.translate("Dialog", u"LAtt", None))
        self.FocalLengthLabel_16.setText(QCoreApplication.translate("Dialog", u"SSoS", None))
        self.FocalLengthLabel_17.setText(QCoreApplication.translate("Dialog", u"SAtt", None))
        self.FocalLengthLabel_18.setText(QCoreApplication.translate("Dialog", u"S. heat", None))
        self.FocalLengthLabel_19.setText(QCoreApplication.translate("Dialog", u"Perfusion", None))
        self.FocalLengthLabel_20.setText(QCoreApplication.translate("Dialog", u"Absorp.", None))
        self.FocalLengthLabel_21.setText(QCoreApplication.translate("Dialog", u"T. cond.", None))
        self.FocalLengthLabel_22.setText(QCoreApplication.translate("Dialog", u"Int. Temp", None))
        self.bForceNoAbsorptionSkullScalpcheckBox.setText(QCoreApplication.translate("Dialog", u"Force no absortpion in skull and scalp", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"Development", None))
    # retranslateUi

