#!/usr/bin/env python3
"""Keep the context of hand-written markup consistent across an lupdate run.

Call sites use the short helper ``TR("...")`` from Localization.py, which asks
Qt for the text in the context "BabelBrain" at run time. ``lupdate`` is told
about TR with ``-tr-function-alias tr+=TR``; because TR carries no context
argument, lupdate files those messages under an *empty* context instead.

So the catalogue is stored with the real context ("BabelBrain", which is what
Linguist shows and what Qt looks up), and this script converts between the two
representations around each lupdate run:

    normalize_context.py --denormalize cat.ts   # "BabelBrain" -> ""
    lupdate ... -ts cat.ts                      # merges, contexts now agree
    normalize_context.py cat.ts                 # "" -> "BabelBrain"

Doing it as a symmetric pair matters: without the --denormalize step lupdate
compares freshly extracted empty-context messages against stored "BabelBrain"
ones, concludes that every string vanished and every string is new, and drops
the translations.

The script is deliberately strict. If lupdate ever files TR() strings somewhere
other than the empty context, an unexpected context name shows up here and the
script exits non-zero instead of letting the catalogue drift out of step with
the run-time lookup (which would silently fall back to the English source).
"""

import sys
import xml.etree.ElementTree as ET

TARGET = 'BabelBrain'
# Contexts generated by pyside6-uic from the two Qt Designer forms.
FORM_CONTEXTS = {'SelFilesDialog', 'OptionsDialog'}

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE TS>\n'


def _name(ctx):
    n = ctx.find('name')
    return (n.text or '') if n is not None else ''


def _key(msg):
    src = msg.find('source')
    cmt = msg.find('comment')
    return (src.text if src is not None else None,
            cmt.text if cmt is not None else None)


def _translated(msg):
    t = msg.find('translation')
    return bool(t is not None and (t.text or '').strip())


def _write(tree, path):
    body = ET.tostring(tree.getroot(), encoding='unicode')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(HEADER + body + '\n')


def _check(root, path):
    """Reject any context this script does not know how to place."""
    bad = sorted({_name(c) for c in root
                  if _name(c) not in ({'', TARGET} | FORM_CONTEXTS)})
    if bad:
        sys.stderr.write(
            "normalize_context.py: unexpected translation context(s) %r in %s.\n"
            "lupdate is no longer filing TR() strings the way this script "
            "expects; the catalogue and the run-time lookup would drift apart.\n"
            % (bad, path))
        return False
    return True


def _merge(root, src_names, dst_name, path):
    """Move every message from the src contexts into dst, preferring a message
    that carries a translation when the same source text appears in both."""
    if not _check(root, path):
        return 1
    sources = [c for c in root if _name(c) in src_names]
    dst = next((c for c in root if _name(c) == dst_name), None)
    if not sources:
        print('normalize_context.py: nothing to move (already %r)' % dst_name)
        return 0
    if dst is None:
        dst = ET.SubElement(root, 'context')
        ET.SubElement(dst, 'name').text = dst_name

    have = {_key(m): m for m in dst.findall('message')}
    moved = 0
    for ctx in sources:
        if ctx is dst:
            continue
        for msg in ctx.findall('message'):
            k = _key(msg)
            cur = have.get(k)
            if cur is None:
                dst.append(msg)
                have[k] = msg
                moved += 1
            elif _translated(msg) and not _translated(cur):
                dst.remove(cur)
                dst.append(msg)
                have[k] = msg
                moved += 1
        root.remove(ctx)
    print('normalize_context.py: moved %d message(s) into %r' % (moved, dst_name))
    return 0


def main(argv):
    denorm = '--denormalize' in argv
    path = [a for a in argv[1:] if not a.startswith('-')][0]
    tree = ET.parse(path)
    root = tree.getroot()
    if denorm:
        rc = _merge(root, {TARGET}, '', path)
    else:
        rc = _merge(root, {''}, TARGET, path)
    if rc:
        return rc
    _write(tree, path)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
