# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QLabel, QPushButton, QScrollBar, QSizePolicy,
    QTabWidget, QTextBrowser, QVBoxLayout, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1309, 757)
        Widget.setLayoutDirection(Qt.LeftToRight)
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(18, 11, 67, 20))
        font = QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.IDLabel = QLabel(Widget)
        self.IDLabel.setObjectName(u"IDLabel")
        self.IDLabel.setGeometry(QRect(96, 11, 111, 21))
        font1 = QFont()
        font1.setPointSize(13)
        font1.setBold(True)
        self.IDLabel.setFont(font1)
        self.IDLabel.setStyleSheet(u"color:rgb(22, 110, 255)")
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(16, 63, 1284, 521))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.USMaskkHzDropDown = QComboBox(self.tab)
        self.USMaskkHzDropDown.addItem("")
        self.USMaskkHzDropDown.setObjectName(u"USMaskkHzDropDown")
        self.USMaskkHzDropDown.setGeometry(QRect(150, 30, 103, 32))
        self.USMaskkHzDropDown.setLayoutDirection(Qt.LeftToRight)
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(27, 35, 120, 20))
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(27, 70, 120, 20))
        self.USPPWSpinBox = QDoubleSpinBox(self.tab)
        self.USPPWSpinBox.setObjectName(u"USPPWSpinBox")
        self.USPPWSpinBox.setGeometry(QRect(150, 67, 90, 22))
        self.USPPWSpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.USPPWSpinBox.setDecimals(0)
        self.USPPWSpinBox.setMinimum(6.000000000000000)
        self.USPPWSpinBox.setMaximum(12.000000000000000)
        self.USPPWSpinBox.setSingleStep(1.000000000000000)
        self.USPPWSpinBox.setValue(6.000000000000000)
        self.USMask = QWidget(self.tab)
        self.USMask.setObjectName(u"USMask")
        self.USMask.setGeometry(QRect(260, 40, 1013, 400))
        self.CalculatePlanningMask = QPushButton(self.tab)
        self.CalculatePlanningMask.setObjectName(u"CalculatePlanningMask")
        self.CalculatePlanningMask.setGeometry(QRect(75, 371, 131, 81))
        self.CalculatePlanningMask.setAutoFillBackground(False)
        self.CalculatePlanningMask.setStyleSheet(u"")
        self.CTZTETabs = QTabWidget(self.tab)
        self.CTZTETabs.setObjectName(u"CTZTETabs")
        self.CTZTETabs.setGeometry(QRect(28, 159, 219, 145))
        self.ZTEtab = QWidget()
        self.ZTEtab.setObjectName(u"ZTEtab")
        self.ZTEtab.setEnabled(True)
        self.verticalLayoutWidget = QWidget(self.ZTEtab)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(12, 59, 193, 40))
        self.LayRange = QVBoxLayout(self.verticalLayoutWidget)
        self.LayRange.setObjectName(u"LayRange")
        self.LayRange.setContentsMargins(0, 0, 0, 0)
        self.RangeLabel = QLabel(self.ZTEtab)
        self.RangeLabel.setObjectName(u"RangeLabel")
        self.RangeLabel.setGeometry(QRect(36, 24, 165, 16))
        self.CTZTETabs.addTab(self.ZTEtab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.HUThresholdSpinBox = QDoubleSpinBox(self.tab_3)
        self.HUThresholdSpinBox.setObjectName(u"HUThresholdSpinBox")
        self.HUThresholdSpinBox.setGeometry(QRect(60, 46, 97, 22))
        self.HUThresholdSpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.HUThresholdSpinBox.setDecimals(0)
        self.HUThresholdSpinBox.setMaximum(5000.000000000000000)
        self.HUThresholdSpinBox.setSingleStep(10.000000000000000)
        self.HUThresholdSpinBox.setValue(300.000000000000000)
        self.label_5 = QLabel(self.tab_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(63, 23, 80, 16))
        self.CTZTETabs.addTab(self.tab_3, "")
        self.TransparencyScrollBar = QScrollBar(self.tab)
        self.TransparencyScrollBar.setObjectName(u"TransparencyScrollBar")
        self.TransparencyScrollBar.setEnabled(False)
        self.TransparencyScrollBar.setGeometry(QRect(974, 452, 194, 20))
        self.TransparencyScrollBar.setMaximum(100)
        self.TransparencyScrollBar.setValue(50)
        self.TransparencyScrollBar.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(850, 451, 115, 20))
        self.HideMarkscheckBox = QCheckBox(self.tab)
        self.HideMarkscheckBox.setObjectName(u"HideMarkscheckBox")
        self.HideMarkscheckBox.setEnabled(False)
        self.HideMarkscheckBox.setGeometry(QRect(272, 448, 100, 28))
        self.tabWidget.addTab(self.tab, "")
        self.outputTerminal = QTextBrowser(Widget)
        self.outputTerminal.setObjectName(u"outputTerminal")
        self.outputTerminal.setGeometry(QRect(7, 607, 1282, 143))
        self.outputTerminal.setReadOnly(True)
        self.label_18 = QLabel(Widget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 590, 114, 16))
        self.label_18.setFont(font)
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(260, 12, 100, 20))
        self.label_3.setFont(font)
        self.TXLabel = QLabel(Widget)
        self.TXLabel.setObjectName(u"TXLabel")
        self.TXLabel.setGeometry(QRect(360, 11, 111, 21))
        self.TXLabel.setFont(font1)
        self.TXLabel.setStyleSheet(u"color:rgb(22, 110, 255)")
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(559, 11, 100, 20))
        self.label_4.setFont(font)
        self.ThermalProfileLabel = QLabel(Widget)
        self.ThermalProfileLabel.setObjectName(u"ThermalProfileLabel")
        self.ThermalProfileLabel.setGeometry(QRect(670, 10, 206, 21))
        self.ThermalProfileLabel.setFont(font1)
        self.ThermalProfileLabel.setStyleSheet(u"color:rgb(22, 110, 255)")
        self.AdvancedOptions = QPushButton(Widget)
        self.AdvancedOptions.setObjectName(u"AdvancedOptions")
        self.AdvancedOptions.setGeometry(QRect(1179, 16, 123, 33))
        self.AdvancedOptions.setAutoFillBackground(False)
        self.AdvancedOptions.setStyleSheet(u"")
        QWidget.setTabOrder(self.USMaskkHzDropDown, self.USPPWSpinBox)
        QWidget.setTabOrder(self.USPPWSpinBox, self.CTZTETabs)
        QWidget.setTabOrder(self.CTZTETabs, self.CalculatePlanningMask)
        QWidget.setTabOrder(self.CalculatePlanningMask, self.HideMarkscheckBox)
        QWidget.setTabOrder(self.HideMarkscheckBox, self.outputTerminal)
        QWidget.setTabOrder(self.outputTerminal, self.HUThresholdSpinBox)
        QWidget.setTabOrder(self.HUThresholdSpinBox, self.tabWidget)

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)
        self.CTZTETabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Target", None))
        self.IDLabel.setText("")
        self.USMaskkHzDropDown.setItemText(0, QCoreApplication.translate("Widget", u"500", None))

        self.label_11.setText(QCoreApplication.translate("Widget", u"US Frequency (kHz)", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"PPW", None))
        self.CalculatePlanningMask.setText(QCoreApplication.translate("Widget", u"Calculate planning\n"
"mask", None))
        self.RangeLabel.setText(QCoreApplication.translate("Widget", u"Normalized ZTE Range", None))
        self.CTZTETabs.setTabText(self.CTZTETabs.indexOf(self.ZTEtab), QCoreApplication.translate("Widget", u"ZTE", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"HU threshold", None))
        self.CTZTETabs.setTabText(self.CTZTETabs.indexOf(self.tab_3), QCoreApplication.translate("Widget", u"CT", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"T1W transparency", None))
        self.HideMarkscheckBox.setText(QCoreApplication.translate("Widget", u"Hide marks", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Widget", u"Step 1 - Calculate Mask", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Terminal output", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"LIFU System", None))
        self.TXLabel.setText("")
        self.label_4.setText(QCoreApplication.translate("Widget", u"Thermal profile", None))
        self.ThermalProfileLabel.setText("")
        self.AdvancedOptions.setText(QCoreApplication.translate("Widget", u"Advanced Options", None))
    # retranslateUi

