TxDiam:                   65.0e-3    #in m
NaturalOutPlaneDistance:  67.0e-3  # in m needs to be confirmed
MinimalTPODistance:       50.0e-3  # in m
MaximalTPODistance:       82.0e-3  # in m
USFrequencies:
    - 300000.0
MaxNegativeDistance:          10.0 #mm
MaxDistanceToSkin:            50.00 #mm
