TxDiam:                   64.0e-3    #in m
NaturalOutPlaneDistance:  52.4e-3  # in m
MinimalTPODistance:       33.6e-3  # in m
MaximalTPODistance:       82.5e-3  # in m
TxDepth:                  14.0e-3    # Back of Tx to outplane
USFrequencies:
    - 500000.0