TxDiam:                   64.0e-3    #in m
NaturalOutPlaneDistance:  52.4e-3  # in m
MinimalTPODistance:       33.6e-3  # in m
MaximalTPODistance:       82.5e-3  # in m
USFrequencies:
    - 500000.0
    - 545000.0
MaxNegativeDistance:          10.0 #mm
MaxDistanceToSkin:            50.00 #mm
Corrections:
    Original:
        - 0.0
        - 0.0 
        - 0.0 
    July2024:
        - 1.20945848e+00
        - -4.22154994e-02
        - -1.16523343e-03