TxDiam:                   64.0e-3    #in m
FocalLength:              150.0e-3  #in m
NaturalOutPlaneDistance:  144.9e-3  # in m
MinimalTPODistance:       50.0e-3  # in m
MaximalTPODistance:       120.0e-3  # in m
USFrequencies:
    - 300000.0
MaxNegativeDistance:          10.0 #mm
MaxDistanceToSkin:            50.00 #mm
InDiameters: #inner diameter of rings
    - 7.7e-3
    - 0.0308
    - 0.0435
    - 0.0532
OutDiameters:  #outer diameter of rings
    - 0.0308
    - 0.0435
    - 0.0532
    - 0.0613
