"""The on-the-wire contract for a custom transducer package.

A custom transducer created in the GUI is a small, self-contained Python package
generated into ``custom_transducers_root()/babel_<Name>/`` -- see
``CreateTransducers.transducer_creator.CustomTransducer._create_tx_files``. In
client/server operation the client has to hand that package to the server, which
imports it to build the Step-2 tab, so both sides need the SAME idea of what a
legitimate package looks like.

This module is that single definition. The client uses it to collect the files to
upload (``package_files``); the server uses it to validate what arrived before
putting the staging directory on ``sys.path`` (``validate_package``).

The validation is deliberately a *shape* check, not a sandbox: the ``.py`` files
still contain whatever the client's BabelBrain generated. What it does buy is
that a client cannot use the staging directory -- which becomes a ``sys.path``
entry -- to drop an arbitrarily-named module there (a ``sitecustomize.py``, or
something shadowing a stdlib name). Combined with the server's
``--serve-allow-custom-transducers`` opt-in, that is the intended boundary; see
server.py's module docstring.
"""

import re

# Names must survive being used as a Python identifier and a path component.
# get_class_name() (transducer_creator) already produces PascalCase from the
# user's YAML name, so this only has to reject the pathological cases.
TX_NAME_RE = re.compile(r'^[A-Za-z][A-Za-z0-9_]{0,63}$')

# Directory holding one transducer, relative to the custom-transducers root.
PACKAGE_DIR_FMT = 'babel_%s'

# Every file _create_tx_files writes, as a format string taking the class name.
# Kept in this order so an error message lists them predictably.
PACKAGE_FILE_FMTS = (
    '__init__.py',
    'babel_%s.py',                  # the Step-2 tab class (babel_tx.py.jinja)
    '%s_form.py',                   # its form (tx_form.py.jinja)
    'babel_integration_%s.py',      # the integration subclass
    'default.yaml',                 # the transducer's parameters
)


class CustomTxPackageError(ValueError):
    """A package that does not match the generated shape."""


def package_dir_name(tx_name):
    """Folder name for a transducer, e.g. ``'babel_MyTx'``."""
    return PACKAGE_DIR_FMT % tx_name


def package_file_names(tx_name):
    """The file names a generated package contains, without any directory."""
    return [fmt % tx_name if '%s' in fmt else fmt for fmt in PACKAGE_FILE_FMTS]


def validate_name(tx_name):
    """Check a transducer name, raising CustomTxPackageError if unusable.

    Also rejects a name that collides with a built-in device: the generated
    package would otherwise shadow (or be shadowed by) a packaged transducer.
    transducer_creator._validate_name refuses these at creation time, but the
    server must not take the client's word for it.
    """
    if not isinstance(tx_name, str) or not TX_NAME_RE.match(tx_name):
        raise CustomTxPackageError(
            "invalid custom transducer name %r: expected a letter followed by "
            "letters, digits or underscores (max 64)" % (tx_name,))

    from Utils.transducer_registry import DEFAULT_TRANSDUCER_NAMES
    if tx_name in DEFAULT_TRANSDUCER_NAMES:
        raise CustomTxPackageError(
            "custom transducer name %r collides with a built-in device" % tx_name)

    return tx_name


def package_files(root, tx_name):
    """Absolute paths of a generated package's files, for upload.

    Args:
        root: the custom-transducers root (``Utils.paths.custom_transducers_root()``).
        tx_name: the transducer's class name, e.g. ``'MyTx'``.

    Raises:
        CustomTxPackageError: the name is unusable, or a file is missing -- which
            means the package was generated by an incompatible version or has
            been edited by hand, and is better caught here than as an ImportError
            halfway through a remote job.
    """
    from pathlib import Path

    validate_name(tx_name)
    folder = Path(root) / package_dir_name(tx_name)
    files = []
    for name in package_file_names(tx_name):
        path = folder / name
        if not path.is_file():
            raise CustomTxPackageError(
                "custom transducer %r is incomplete: %s is missing from %s"
                % (tx_name, name, folder))
        files.append(path)
    return files


def validate_package(folder, tx_name):
    """Check a STAGED package before it is made importable.

    Requires exactly the generated file set: nothing missing (so the import will
    not fail later) and nothing extra (so the staging directory cannot carry an
    unexpected module into ``sys.path``).

    Args:
        folder: the staged ``babel_<Name>`` directory.
        tx_name: the transducer's class name.

    Raises:
        CustomTxPackageError: on an unusable name, a missing file, or any file
            the generated shape does not account for.
    """
    from pathlib import Path

    validate_name(tx_name)
    folder = Path(folder)
    if not folder.is_dir():
        raise CustomTxPackageError("staged transducer directory is missing: %s" % folder)

    expected = set(package_file_names(tx_name))
    present = set()
    for entry in folder.iterdir():
        if not entry.is_file() or entry.is_symlink():
            raise CustomTxPackageError(
                "unexpected entry %r in staged transducer %r (only the %d "
                "generated files are allowed)" % (entry.name, tx_name, len(expected)))
        present.add(entry.name)

    missing = sorted(expected - present)
    if missing:
        raise CustomTxPackageError(
            "staged transducer %r is missing: %s" % (tx_name, ", ".join(missing)))

    extra = sorted(present - expected)
    if extra:
        raise CustomTxPackageError(
            "staged transducer %r carries unexpected file(s): %s"
            % (tx_name, ", ".join(extra)))

    return folder
