TxFoc:                    53.2e-3 #Tx focal length
TxDiam:                   58.0e-3 # Tx aperture diameter

MinimalZSteering:      -30.0e-3  # in m
MaximalZSteering:       30.0e-3  # in m
MinimalXSteering:      -20.0e-3  # in m
MaximalXSteering:       20.0e-3  # in m
MinimalYSteering:      -20.0e-3  # in m
MaximalYSteering:       20.0e-3  # in m

MinimalDistanceConeToFocus:       10.0e-3  # in m
MaximalDistanceConeToFocus:       42.0e-3  # in m # a couple mm away of the outplane
DefaultDistanceConeToFocus:       25.0e-3  # in m

USFrequencies:
    - 1000000.0


PlanTUS: #This information is to interface with the PlanTUS tool - Synthectic
    1000000.0:
        FocalDistanceList:
            - 20.2
            - 23.2
            - 26.2
            - 29.2
            - 32.2
            - 35.2
            - 38.2
            - 41.2
            - 44.2
            - 47.2
            - 50.2
            - 53.2
            - 56.2
            - 59.2
            - 62.2
            - 65.2
            - 68.2
            - 71.2
            - 74.2
            - 77.2
            - 80.2
            - 83.2
            - 86.2
            - 89.2
            - 92.2
            - 95.2
            - 98.2
            - 101.2
            - 104.2
        FHMLList:
            - 4.4
            - 3.3
            - 3.6
            - 3.9
            - 4.5
            - 5.3
            - 5.9
            - 6.6
            - 7.4
            - 8.3
            - 9.2
            - 10.2
            - 11.1
            - 12.2
            - 13.4
            - 14.4
            - 15.8
            - 17.0
            - 18.2
            - 19.5
            - 20.9
            - 22.2
            - 23.7
            - 25.2
            - 26.7
            - 28.2
            - 29.9
            - 31.5
            - 33.2
