name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request_review_comment:
    types: [created, edited]
jobs:
  Run-test-mac-arm64:
    #if: ${{ (github.event.issue.pull_request) && (github.event.comment.body== '[macarm64]') }}
    runs-on: [self-hosted, macOS, ARM64]
    env:
      github_username: ${{ github.actor }}
      github_id: ${{ github.actor_id }}
      github_comment: ${{ github.event.comment.body }}
    defaults:
     run:
       shell: zsh {0}
    steps:
      - name: execute if macarm64
        run: |
          echo "username  $github_username"
          echo "github_id  $github_id"
          echo "comment  $github_comment" 
          echo "Running pytest mac arm 64"
      #&& (needs.rules.outputs.branch_name != 'staging') }}
      # - name: Activate Conda
      #   run: |
      #     . /Users/spichardo/miniconda3/etc/profile.d/conda.sh
      #     conda activate BabelBrain
      # - name: Copy config files
      #   run: |
      #    cp /Users/spichardo/Public/TempForSim/config.ini Tests/
      # - name: run pytest
      #   run: |
      #     . /Users/spichardo/miniconda3/etc/profile.d/conda.sh
      #     conda activate BabelBrain
      #     pytest Tests -k 'test_step1_normal[SDR_0p55-CT-H317-Deep_Target-brainsight]' 
