name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
     run:
       shell: zsh {0}
    steps:
      #- uses: actions/checkout@v2
      - name: Activate Conda
        run: |
          . /Users/spichardo/miniconda3/etc/profile.d/conda.sh
          conda activate BabelBrain
      - name: Copy config files
        run: |
         cp /Users/spichardo/Public/TempForSim/config.ini Tests/
      - name: run pytest
        run: |
          . /Users/spichardo/miniconda3/etc/profile.d/conda.sh
          conda activate BabelBrain
          pytest Tests -k 'test_step1_normal[SDR_0p55-CT-H317-Deep_Target-brainsight]' 
